name: django-tpl
services:
  database:
    image: postgres:16.10-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d:ro
      - postgres:/var/lib/postgresql/data

  mail:
    image: docker.io/mailhog/mailhog:v1.0.1
    container_name: mailhog
    ports:
      - "${SMTP_PORT:-1025}:1025"
      - "${SMTP_WEB_PORT:-8025}:8025"

  staticfiles:
    image: docker.io/caddy:2.10.2-alpine
    container_name: caddy
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "${STATIC_PORT:-8888}:80"
    volumes:
      - ../staticfiles:/srv:ro
      - ./caddy:/etc/caddy:ro
      - caddy_data:/data
      - caddy_config:/config

  pgadmin:
    image: docker.io/dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin@devsforge.org
      - PGADMIN_DEFAULT_PASSWORD=pgadmin
      - PGADMIN_CONFIG_SERVERMODE=False
    ports:
      - "${PGADMIN_PORT:-8032}:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json:ro
    depends_on:
      - database

volumes:
  postgres:
    driver: local
  caddy_data:
  caddy_config:
  pgadmin:
